create database grocery;
use grocery;

-- Supplier table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

-- Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from supplier;
select*from categories;
select*from employees;
select*from customers;
select*from products;
select*from orders;
select*from order_details;

-- Analysis Questions

-- 1. Customer Insights

-- How many unique customers have placed orders?
select  count(cust_id) as unique_customers
from orders;
-- Which customers have placed the highest number of orders?
select c.cust_name,count(o.ord_id) as total_orders from customers c
join orders o  on 
c.cust_id=o.cust_id
group by c.cust_name
order by total_orders desc;
-- What is the total and average purchase value per customer?
select c.cust_name,sum(total_price)as total_spent,avg(total_price) as avg_spent
from customers c 
join orders o on
c.cust_id=o.cust_id
join order_details od ON 
o.ord_id = od.ord_id
group by c.cust_name;
-- Who are the top 5 customers by total purchase amount?
select c.cust_name,Sum(total_price) as total_spent
from customers c
join orders o on 
c.cust_id = o.cust_id
join order_details od on 
o.ord_id = od.ord_id
group by c.cust_name
order by total_spent desc
limit 5;

-- 2.product performance

-- How many products exist in each category?
select c. cat_name,count(prod_id)as total_products
from categories c 
join products p on
c.cat_id=p.cat_id
group by c.cat_name;
-- What is the average price of products by category?
select c.cat_name,avg(price) as avg_products
from categories c 
join products p on
c.cat_id=p.cat_id
group by c.cat_name;
-- Which products have the highest total sales volume (by quantity)?
select p.prod_name, SUM(od.quantity) as total_quantity
from products p
join order_details od on 
p.prod_id = od.prod_id
group by p.prod_name
order by total_quantity desc;
-- What is the total revenue generated by each product?
select p.prod_name,sum(od.total_price) as total_revenue
from products p 
join order_details od on
p.prod_id=od.prod_id
group by p.prod_name
order by total_revenue desc;
-- How do product sales vary by category and supplier?
select c.cat_name, s.sup_name,SUM(od.total_price) as revenue
from order_details od
join products p on 
od.prod_id = p.prod_id
join categories c on 
p.cat_id = c.cat_id
join supplier s on p.sup_id = s.sup_id
group by c.cat_name, s.sup_name;

-- 3.Sales and Order Trends

-- How many orders have been placed in total?
select count(ord_id) from orders;
-- What is the average value per order?
select avg(order_total)
from (
    select ord_id, SUM(total_price) as order_total
    from order_details
    group by ord_id
) as sub;
-- On which dates were the most orders placed?
select order_date ,count(*)as total_orders from orders
group by order_date
order by total_orders desc;
-- What are the monthly trends in order volume and revenue?
select month(str_to_date(order_date,'%Y-%m-%d')) as month,sum(od.total_price) as revenue
from orders o
join order_details od on o.ord_id = od.ord_id
group by month;
-- How do order patterns vary across weekdays and weekends?
select
case
    when  dayofweek(str_to_date(order_date,'%Y-%m-%d')) in (1,7)
    then 'Weekend'
    else 'Weekday'
end as day_type,
count(*) as total_orders
from orders
group by day_type;

-- 4.Supplier Contribution

-- How many suppliers are there in the database?
select count(sup_id) from supplier;
-- Which supplier provides the most products?
select s.sup_name,count(p.prod_id) as total_products
from supplier s 
join products p  on
s.sup_id=p.sup_id
group by s.sup_name
order by total_products desc;
-- What is the average price of products from each supplier?
select s.sup_name,avg(p.price) as avg_price
from supplier s 
join products p on
s.sup_id=p.sup_id
group by s.sup_name;
-- Which suppliers contribute the most to total product sales (by revenue)?
select s.sup_name, SUM(od.total_price) as total_revenue
from supplier s
join products p on 
s.sup_id = p.sup_id
join order_details od on 
p.prod_id = od.prod_id
group by s.sup_name
order by total_revenue desc;

-- 5.Employee Performance

-- How many employees have processed orders?
select count(emp_id) from orders;
-- Which employees have handled the most orders?
select e.emp_name, count(o.ord_id) as total_orders
from employees e
join orders o on e.emp_id = o.emp_id
group by e.emp_name
order by total_orders desc;
-- What is the total sales value processed by each employee?
select e.emp_name, sum(od.total_price) as total_sales
from employees e
join orders o on e.emp_id = o.emp_id
join order_details od on o.ord_id = od.ord_id
group by e.emp_name;
-- What is the average order value handled per employee?
select e.emp_name,
       avg(order_total) as avg_order_value
from(
    select o.emp_id, o.ord_id,
           sum(od.total_price) as order_total
    from orders o
    join order_details od on o.ord_id = od.ord_id
    group by o.emp_id, o.ord_id
) sub
join employees e on sub.emp_id = e.emp_id
group by e.emp_name;

-- 6. Order Details Deep Dive

-- What is the relationship between quantity ordered and total price?
select quantity, total_price from order_details;
-- What is the average quantity ordered per product?
select p.prod_name, avg(od.quantity) as avg_quantity
from products p
join order_details od on p.prod_id = od.prod_id
group by p.prod_name;
-- How does the unit price vary across products and orders?
select prod_id, avg(each_price) as avg_unit_price
from order_details
group by prod_id;

